server:
  port: 8085
pokemon-external-api: https://pokeapi.co/api/v2/pokemon

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest-template-pokemon?createDatabaseIfNotExist=true
    username: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true